### ISSUE TITLE
dataset split files

### ISSUE THREAD

**Issue by yizhixiaowangba** [RangeWING/MetaWeather#1]
Thank you for providing the code for MetaWeather. I have successfully set up the environment and loaded the pre-trained models. However, I am having difficulty finding the dataset split files (e.g., BID-case1-train.txt, BID-case2-test.txt, etc.) that are mentioned in the README for performing meta-train and meta-test phases.
Could you kindly provide the dataset split files or clarify how to split the datasets for meta-training and meta-testing? This information would be very helpful for reproducing your results and running further experiments.

**Comment by RangeWING** [comment]
Thank you for your interest in our work!

Please find the split files we used below:
https://drive.google.com/file/d/1zGc0KSCB8lGUc35LmNwmfvkevo5zlOtP/view?usp=drive_link

**Comment by yizhixiaowangba** [comment]
Thank you very much for your reply and wish you all the best!

**Comment by YDB04234** [comment]
How to get the dataset Rain13k ，snow100 and so on 。How can they be set up as directories and text files?

**Comment by yizhixiaowangba45** [comment]
You can get the rain13k from https://drive.google.com/drive/folders/1PDWggNh8ylevFmrjo-JEvlmqsDlWWvZs, snow 100k from https://drive.google.com/drive/folders/11kGq5VB6hyEx-GTONvH9Z4cH7EhpjaJ_
You can refer to the supplementary materials in the paper to organize these datasets

**Comment by yizhixiaowangba** [comment]
> How to get the dataset Rain13k ，snow100 and so on 。How can they be set up as directories and text files?
You can get the rain13k from https://drive.google.com/drive/folders/1PDWggNh8ylevFmrjo-JEvlmqsDlWWvZs, snow 100k from https://drive.google.com/drive/folders/11kGq5VB6hyEx-GTONvH9Z4cH7EhpjaJ_
You can refer to the supplementary materials in the paper to organize these datasets

**Comment by YDB04234** [comment]
Thank you very much!  but how to get rain13k.txt and so on

**Comment by YDB04234** [comment]
Sorry, but I really don't understand how to set the directory of the training data set and the txt file. Could you show yours to me?

**Comment by yizhixiaowangba** [comment]
You can use this script to complete the annotation of the dataset
https://drive.google.com/file/d/12Ap7xvWX3CYhCoRi0tG7xTk3BbxXBpVB/view?usp=sharing

**Comment by YDB04234** [comment]
Thank you very much for your great help, big shot. I still have one more question. Have you ever encountered this problem? 
training,
--- no weight loaded ---
Tasks: ['rain13k', 'snow100k', 'raindrop', 'fog']
Traceback (most recent call last):
  File "/root/data1/MetaWeather/train.py", line 117, in <module>
    support_data = generate_support_data(config, data_path='support_data1.pth', split='train')
  File "/root/data1/MetaWeather/dataset/factory.py", line 245, in generate_support_data
    dataset = create_unit_dataset(config, task=task, split=split, mode='center_crop', dset_size=None, image_augmentation=False)
  File "/root/data1/MetaWeather/dataset/factory.py", line 107, in create_unit_dataset
    return IRUnitDataset(crop_size=(config.img_size, config.img_size), 
  File "/root/data1/MetaWeather/dataset/base.py", line 41, in __init__
    self.gt_names = [self._get_gt_name(n) for n in input_names]
  File "/root/data1/MetaWeather/dataset/base.py", line 41, in <listcomp>
    self.gt_names = [self._get_gt_name(n) for n in input_names]
  File "/root/data1/MetaWeather/dataset/base.py", line 87, in _get_gt_name
    raise NotImplementedError(f'Error: input and gt names are the same. Did you implement the gt name converter function correctly?')
NotImplementedError: Error: input and gt names are the same. Did you implement the gt name converter function correctly?

**Comment by YDB04234** [comment]
Excuse me. Did you succeed in reproducing it?
